# Generated by Django 5.2.6 on 2025-11-22 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المشروع')),
                ('description', models.TextField(verbose_name='وصف المشروع')),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المطلوب')),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المجموع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='صورة المشروع')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='صاحب المشروع')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المستثمر')),
                ('invested_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='projects.project')),
            ],
            options={
                'ordering': ['-invested_at'],
            },
        ),
    ]
